name: CI

on:
  push:
    branches: 
      - main
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: set up JDK
         uses: actions/setup-java@v1
         with:
          java-version: 8

       - name: "Run detekt"
         uses: natiginfo/action-detekt-all@1.10.0
         with:
           args: --fail-fast --config detekt-config.yml
           
       - name: Run Android Linter
         run: ./gradlew lintDebug
         
       - name: Run Unit Tests
         run: ./gradlew testDebug
