name: CI

on:
  push:
    branches: 
      - main
      - feature/*
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      
      - name: JDK Setup
        uses: actions/setup-java@v1
        with:
          java-version: 8
          
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          patch:  ~/.gradle/caches
          key:  gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          
      - name: "Detekt"
        uses: natiginfo/action-detekt-all@1.10.0
        with:
          args: --fail-fast --config detekt-config.yml
           
      - name: Android Lint
        run: ./gradlew lintDebug
  
  unit-test: 
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: JDK Setup
        uses: actions/setup-java@v1
        with:
          java-version: 8
          
      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          patch:  ~/.gradle/caches
          key:  gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          
      - name: Run Unit Tests
        run: ./gradlew testDebug
